export const RETRIEVE_CLIENT_INFO = "RETRIEVE_CLIENT_INFO";
export const DOCUMENTS_CLIENT_NAME = "DOCUMENTS_CLIENT_NAME";
export const ACCESS_REVOKE = "ACCESS_REVOKE";
export const CLIENT_ALL_INFO = "CLIENT_ALL_INFO";
export const USER_COLLEAGUES = "USER_COLLEAGUES";
export const INVITED_EMAIL_SUCCESS = "INVITED_EMAIL_SUCCESS";
export const INVITED_EMAIL_FAILURE = "INVITED_EMAIL_FAILURE";
