export const LOANS_OVERVIEW_INFO = "LOANS_OVERVIEW_INFO";
export const ALL_PURCHASE = "ALL_PURCHASE";
export const REPAYMENT_INFO = "REPAYMENT_INFO";
export const REPAYMENT_INFO_POST = "REPAYMENT_INFO_POST";
