export const STAFF_DASHBOARD_RESULT = "STAFF_DASHBOARD_RESULT";
export const STAFF_DETAILS_GET = "STAFF_DETAILS_GET";
export const USER_UNDER_CLIENT_GET = "USER_UNDER_CLIENT_GET";
export const MAKE_CREDIT_OFFER = "MAKE_CREDIT_OFFER";
export const CREDIT_REQUEST_VIEW = "CREDIT_REQUEST_VIEW";
export const ALL_PURCHASE_ORDERS = "ALL_PURCHASE_ORDERS";
